name: Deployment 
on: 
  push:
   branches:
      - develop
jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: 
      name: development
      url: https://github.com
    steps:
      - name: deploy 
      -  run: ls -la