name: Deployment 
on: 
  # Trigger the workflow on push or pull request events but only for the develop branch
  push:
   branches: [develop]
jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: 
      name: development
      url: https://github.com
    steps:
      
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v